[package]
name = "api"
version = "0.1.0"
authors = ["Alexandre Senges <alexandre@senges.ch>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
log = "0.4.8"
serde = "1.0.104"
serde_json = "1.0.47"
actix-cors = "0.2.0"
nalgebra = "0.18"
load-dotenv = "0.1.1"